### ISSUE TITLE
请问未知错误怎么解决？

### ISSUE THREAD

**Issue by msute** [laipz8200/IDCardIdentify#1]
![image](https://user-images.githubusercontent.com/52910627/69041129-eaf3bb00-0a29-11ea-8506-b61ee25c760e.png)

**Comment by laipz8200** [comment]
矫正未知错误通常是待识别的图像中身份证明暗不一或与背景色过于接近，导致无法识别出身份证边缘。

**Comment by msute** [comment]
> 矫正未知错误通常是待识别的图像中身份证明暗不一或与背景色过于接近，导致无法识别出身份证边缘。
我是百度找了几张图都不行   背景一定要深浅分离才行？请问这种问题怎么改善好呢？

**Comment by msute** [comment]
方便加个qq让我请教几个问题吗  现在试了韦小宝那张图还是不行
